export const countries = [
    { name: "Afghanistan", alpha2: "AF", dialCode: "+93" },
    { name: "Albania", alpha2: "AL", dialCode: "+355" },
    { name: "Algeria", alpha2: "DZ", dialCode: "+213" },
    { name: "Andorra", alpha2: "AD", dialCode: "+376" },
    { name: "Angola", alpha2: "AO", dialCode: "+244" },
    { name: "Antigua and Barbuda", alpha2: "AG", dialCode: "+1‑268" },
    { name: "Argentina", alpha2: "AR", dialCode: "+54" },
    { name: "Armenia", alpha2: "AM", dialCode: "+374" },
    { name: "Australia", alpha2: "AU", dialCode: "+61" },
    { name: "Austria", alpha2: "AT", dialCode: "+43" },
    { name: "Azerbaijan", alpha2: "AZ", dialCode: "+994" },
    { name: "Bahamas", alpha2: "BS", dialCode: "+1‑242" },
    { name: "Bahrain", alpha2: "BH", dialCode: "+973" },
    { name: "Bangladesh", alpha2: "BD", dialCode: "+880" },
    { name: "Barbados", alpha2: "BB", dialCode: "+1‑246" },
    { name: "Belarus", alpha2: "BY", dialCode: "+375" },
    { name: "Belgium", alpha2: "BE", dialCode: "+32" },
    { name: "Belize", alpha2: "BZ", dialCode: "+501" },
    { name: "Benin", alpha2: "BJ", dialCode: "+229" },
    { name: "Bhutan", alpha2: "BT", dialCode: "+975" },
    { name: "Bolivia", alpha2: "BO", dialCode: "+591" },
    { name: "Bosnia and Herzegovina", alpha2: "BA", dialCode: "+387" },
    { name: "Botswana", alpha2: "BW", dialCode: "+267" },
    { name: "Brazil", alpha2: "BR", dialCode: "+55" },
    { name: "Brunei", alpha2: "BN", dialCode: "+673" },
    { name: "Bulgaria", alpha2: "BG", dialCode: "+359" },
    { name: "Burkina Faso", alpha2: "BF", dialCode: "+226" },
    { name: "Burundi", alpha2: "BI", dialCode: "+257" },
    { name: "Cabo Verde", alpha2: "CV", dialCode: "+238" },
    { name: "Cambodia", alpha2: "KH", dialCode: "+855" },
    { name: "Cameroon", alpha2: "CM", dialCode: "+237" },
    { name: "Canada", alpha2: "CA", dialCode: "+1" },
    { name: "Central African Republic", alpha2: "CF", dialCode: "+236" },
    { name: "Chad", alpha2: "TD", dialCode: "+235" },
    { name: "Chile", alpha2: "CL", dialCode: "+56" },
    { name: "China", alpha2: "CN", dialCode: "+86" },
    { name: "Colombia", alpha2: "CO", dialCode: "+57" },
    { name: "Comoros", alpha2: "KM", dialCode: "+269" },
    { name: "Congo (Republic)", alpha2: "CG", dialCode: "+242" },
    { name: "Congo (Democratic Republic)", alpha2: "CD", dialCode: "+243" },
    { name: "Costa Rica", alpha2: "CR", dialCode: "+506" },
    { name: "Côte d'Ivoire", alpha2: "CI", dialCode: "+225" },
    { name: "Croatia", alpha2: "HR", dialCode: "+385" },
    { name: "Cuba", alpha2: "CU", dialCode: "+53" },
    { name: "Cyprus", alpha2: "CY", dialCode: "+357" },
    { name: "Czech Republic", alpha2: "CZ", dialCode: "+420" },
    { name: "Denmark", alpha2: "DK", dialCode: "+45" },
    { name: "Djibouti", alpha2: "DJ", dialCode: "+253" },
    { name: "Dominica", alpha2: "DM", dialCode: "+1‑767" },
    { name: "Dominican Republic", alpha2: "DO", dialCode: "+1‑809" },
    { name: "Ecuador", alpha2: "EC", dialCode: "+593" },
    { name: "Egypt", alpha2: "EG", dialCode: "+20" },
    { name: "El Salvador", alpha2: "SV", dialCode: "+503" },
    { name: "Equatorial Guinea", alpha2: "GQ", dialCode: "+240" },
    { name: "Eritrea", alpha2: "ER", dialCode: "+291" },
    { name: "Estonia", alpha2: "EE", dialCode: "+372" },
    { name: "Eswatini", alpha2: "SZ", dialCode: "+268" },
    { name: "Ethiopia", alpha2: "ET", dialCode: "+251" },
    { name: "Fiji", alpha2: "FJ", dialCode: "+679" },
    { name: "Finland", alpha2: "FI", dialCode: "+358" },
    { name: "France", alpha2: "FR", dialCode: "+33" },
    { name: "Gabon", alpha2: "GA", dialCode: "+241" },
    { name: "Gambia", alpha2: "GM", dialCode: "+220" },
    { name: "Georgia", alpha2: "GE", dialCode: "+995" },
    { name: "Germany", alpha2: "DE", dialCode: "+49" },
    { name: "Ghana", alpha2: "GH", dialCode: "+233" },
    { name: "Greece", alpha2: "GR", dialCode: "+30" },
    { name: "Grenada", alpha2: "GD", dialCode: "+1‑473" },
    { name: "Guatemala", alpha2: "GT", dialCode: "+502" },
    { name: "Guinea", alpha2: "GN", dialCode: "+224" },
    { name: "Guinea‑Bissau", alpha2: "GW", dialCode: "+245" },
    { name: "Guyana", alpha2: "GY", dialCode: "+592" },
    { name: "Haiti", alpha2: "HT", dialCode: "+509" },
    { name: "Honduras", alpha2: "HN", dialCode: "+504" },
    { name: "Hungary", alpha2: "HU", dialCode: "+36" },
    { name: "Iceland", alpha2: "IS", dialCode: "+354" },
    { name: "India", alpha2: "IN", dialCode: "+91" },
    { name: "Indonesia", alpha2: "ID", dialCode: "+62" },
    { name: "Iran", alpha2: "IR", dialCode: "+98" },
    { name: "Iraq", alpha2: "IQ", dialCode: "+964" },
    { name: "Ireland", alpha2: "IE", dialCode: "+353" },
    { name: "Israel", alpha2: "IL", dialCode: "+972" },
    { name: "Italy", alpha2: "IT", dialCode: "+39" },
    { name: "Jamaica", alpha2: "JM", dialCode: "+1‑876" },
    { name: "Japan", alpha2: "JP", dialCode: "+81" },
    { name: "Jordan", alpha2: "JO", dialCode: "+962" },
    { name: "Kazakhstan", alpha2: "KZ", dialCode: "+7" },
    { name: "Kenya", alpha2: "KE", dialCode: "+254" },
    { name: "Kiribati", alpha2: "KI", dialCode: "+686" },
    { name: "Kuwait", alpha2: "KW", dialCode: "+965" },
    { name: "Kyrgyzstan", alpha2: "KG", dialCode: "+996" },
    { name: "Laos", alpha2: "LA", dialCode: "+856" },
    { name: "Latvia", alpha2: "LV", dialCode: "+371" },
    { name: "Lebanon", alpha2: "LB", dialCode: "+961" },
    { name: "Lesotho", alpha2: "LS", dialCode: "+266" },
    { name: "Liberia", alpha2: "LR", dialCode: "+231" },
    { name: "Libya", alpha2: "LY", dialCode: "+218" },
    { name: "Liechtenstein", alpha2: "LI", dialCode: "+423" },
    { name: "Lithuania", alpha2: "LT", dialCode: "+370" },
    { name: "Luxembourg", alpha2: "LU", dialCode: "+352" },
    { name: "Madagascar", alpha2: "MG", dialCode: "+261" },
    { name: "Malawi", alpha2: "MW", dialCode: "+265" },
    { name: "Malaysia", alpha2: "MY", dialCode: "+60" },
    { name: "Maldives", alpha2: "MV", dialCode: "+960" },
    { name: "Mali", alpha2: "ML", dialCode: "+223" },
    { name: "Malta", alpha2: "MT", dialCode: "+356" },
    { name: "Marshall Islands", alpha2: "MH", dialCode: "+692" },
    { name: "Mauritania", alpha2: "MR", dialCode: "+222" },
    { name: "Mauritius", alpha2: "MU", dialCode: "+230" },
    { name: "Mexico", alpha2: "MX", dialCode: "+52" },
    { name: "Micronesia (Federated States)", alpha2: "FM", dialCode: "+691" },
    { name: "Moldova", alpha2: "MD", dialCode: "+373" },
    { name: "Monaco", alpha2: "MC", dialCode: "+377" },
    { name: "Mongolia", alpha2: "MN", dialCode: "+976" },
    { name: "Montenegro", alpha2: "ME", dialCode: "+382" },
    { name: "Morocco", alpha2: "MA", dialCode: "+212" },
    { name: "Mozambique", alpha2: "MZ", dialCode: "+258" },
    { name: "Myanmar", alpha2: "MM", dialCode: "+95" },
    { name: "Namibia", alpha2: "NA", dialCode: "+264" },
    { name: "Nauru", alpha2: "NR", dialCode: "+674" },
    { name: "Nepal", alpha2: "NP", dialCode: "+977" },
    { name: "Netherlands", alpha2: "NL", dialCode: "+31" },
    { name: "New Zealand", alpha2: "NZ", dialCode: "+64" },
    { name: "Nicaragua", alpha2: "NI", dialCode: "+505" },
    { name: "Niger", alpha2: "NE", dialCode: "+227" },
    { name: "Nigeria", alpha2: "NG", dialCode: "+234" },
    { name: "North Macedonia", alpha2: "MK", dialCode: "+389" },
    { name: "Norway", alpha2: "NO", dialCode: "+47" },
    { name: "Oman", alpha2: "OM", dialCode: "+968" },
    { name: "Pakistan", alpha2: "PK", dialCode: "+92" },
    { name: "Palau", alpha2: "PW", dialCode: "+680" },
    { name: "Palestine", alpha2: "PS", dialCode: "+970" },
    { name: "Panama", alpha2: "PA", dialCode: "+507" },
    { name: "Papua New Guinea", alpha2: "PG", dialCode: "+675" },
    { name: "Paraguay", alpha2: "PY", dialCode: "+595" },
    { name: "Peru", alpha2: "PE", dialCode: "+51" },
    { name: "Philippines", alpha2: "PH", dialCode: "+63" },
    { name: "Poland", alpha2: "PL", dialCode: "+48" },
    { name: "Portugal", alpha2: "PT", dialCode: "+351" },
    { name: "Qatar", alpha2: "QA", dialCode: "+974" },
    { name: "Romania", alpha2: "RO", dialCode: "+40" },
    { name: "Russia", alpha2: "RU", dialCode: "+7" },
    { name: "Rwanda", alpha2: "RW", dialCode: "+250" },
    { name: "Saint Kitts and Nevis", alpha2: "KN", dialCode: "+1‑869" },
    { name: "Saint Lucia", alpha2: "LC", dialCode: "+1‑758" },
    { name: "Saint Vincent and the Grenadines", alpha2: "VC", dialCode: "+1‑784" },
    { name: "Samoa", alpha2: "WS", dialCode: "+685" },
    { name: "San Marino", alpha2: "SM", dialCode: "+378" },
    { name: "Sao Tome and Principe", alpha2: "ST", dialCode: "+239" },
    { name: "Saudi Arabia", alpha2: "SA", dialCode: "+966" },
    { name: "Senegal", alpha2: "SN", dialCode: "+221" },
    { name: "Serbia", alpha2: "RS", dialCode: "+381" },
    { name: "Seychelles", alpha2: "SC", dialCode: "+248" },
    { name: "Sierra Leone", alpha2: "SL", dialCode: "+232" },
    { name: "Singapore", alpha2: "SG", dialCode: "+65" },
    { name: "Slovakia", alpha2: "SK", dialCode: "+421" },
    { name: "Slovenia", alpha2: "SI", dialCode: "+386" },
    { name: "Solomon Islands", alpha2: "SB", dialCode: "+677" },
    { name: "Somalia", alpha2: "SO", dialCode: "+252" },
    { name: "South Africa", alpha2: "ZA", dialCode: "+27" },
    { name: "South Sudan", alpha2: "SS", dialCode: "+211" },
    { name: "Spain", alpha2: "ES", dialCode: "+34" },
    { name: "Sri Lanka", alpha2: "LK", dialCode: "+94" },
    { name: "Sudan", alpha2: "SD", dialCode: "+249" },
    { name: "Suriname", alpha2: "SR", dialCode: "+597" },
    { name: "Sweden", alpha2: "SE", dialCode: "+46" },
    { name: "Switzerland", alpha2: "CH", dialCode: "+41" },
    { name: "Syria", alpha2: "SY", dialCode: "+963" },
    { name: "Tajikistan", alpha2: "TJ", dialCode: "+992" },
    { name: "Tanzania", alpha2: "TZ", dialCode: "+255" },
    { name: "Thailand", alpha2: "TH", dialCode: "+66" },
    { name: "Timor‑Leste", alpha2: "TL", dialCode: "+670" },
    { name: "Togo", alpha2: "TG", dialCode: "+228" },
    { name: "Tonga", alpha2: "TO", dialCode: "+676" },
    { name: "Trinidad and Tobago", alpha2: "TT", dialCode: "+1‑868" },
    { name: "Tunisia", alpha2: "TN", dialCode: "+216" },
    { name: "Turkey", alpha2: "TR", dialCode: "+90" },
    { name: "Turkmenistan", alpha2: "TM", dialCode: "+993" },
    { name: "Tuvalu", alpha2: "TV", dialCode: "+688" },
    { name: "Uganda", alpha2: "UG", dialCode: "+256" },
    { name: "Ukraine", alpha2: "UA", dialCode: "+380" },
    { name: "United Arab Emirates", alpha2: "AE", dialCode: "+971" },
    { name: "United Kingdom", alpha2: "GB", dialCode: "+44" },
    { name: "United States", alpha2: "US", dialCode: "+1" },
    { name: "Uruguay", alpha2: "UY", dialCode: "+598" },
    { name: "Uzbekistan", alpha2: "UZ", dialCode: "+998" },
    { name: "Vanuatu", alpha2: "VU", dialCode: "+678" },
    { name: "Vatican City", alpha2: "VA", dialCode: "+39" },
    { name: "Venezuela", alpha2: "VE", dialCode: "+58" },
    { name: "Vietnam", alpha2: "VN", dialCode: "+84" },
    { name: "Yemen", alpha2: "YE", dialCode: "+967" },
    { name: "Zambia", alpha2: "ZM", dialCode: "+260" },
    { name: "Zimbabwe", alpha2: "ZW", dialCode: "+263" }
];
