import { AccessTimeOutlined, DirectionsCarOutlined, EmojiFoodBeverageOutlined, EmojiNatureOutlined, EmojiObjectsOutlined, EmojiSymbolsOutlined, FlagOutlined, InsertEmoticonOutlined, SportsBaseballOutlined } from "@mui/icons-material";

export const emojis = [
    {
        id: '1',
        category: 'Recent',
        icon: AccessTimeOutlined,
        emojis: []
    },
    {
        id: '2',
        category: 'Smileys & People',
        icon: InsertEmoticonOutlined,
        emojis: [
            { title: 'grinning face', emoji: '😀' },
            { title: 'grinning face with big eyes', emoji: '😃' },
            { title: 'grinning face with smiling eyes', emoji: '😄' },
            { title: 'beaming face with smiling eyes', emoji: '😁' },
            { title: 'grinning squinting face', emoji: '😆' },
            { title: 'grinning face with sweat', emoji: '😅' },
            { title: 'rolling on the floor laughing', emoji: '🤣' },
            { title: 'face with tears of joy', emoji: '😂' },
            { title: 'slightly smiling face', emoji: '🙂' },
            { title: 'upside-down face', emoji: '🙃' },
            { title: 'melting face', emoji: '🫠' },
            { title: 'winking face', emoji: '😉' },
            { title: 'smiling face with smiling eyes', emoji: '😊' },
            { title: 'smiling face with halo', emoji: '😇' },
            { title: 'smiling face with hearts', emoji: '🥰' },
            { title: 'smiling face with heart-eyes', emoji: '😍' },
            { title: 'star-struck', emoji: '🤩' },
            { title: 'face blowing a kiss', emoji: '😘' },
            { title: 'kissing face', emoji: '😗' },
            { title: 'smiling face', emoji: '☺️' },
            { title: 'kissing face with closed eyes', emoji: '😚' },
            { title: 'kissing face with smiling eyes', emoji: '😙' },
            { title: 'smiling face with tear', emoji: '🥲' },
            { title: 'face savoring food', emoji: '😋' },
            { title: 'face with tongue', emoji: '😛' },
            { title: 'winking face with tongue', emoji: '😜' },
            { title: 'zany face', emoji: '🤪' },
            { title: 'squinting face with tongue', emoji: '😝' },
            { title: 'money-mouth face', emoji: '🤑' },
            { title: 'smiling face with open hands', emoji: '🤗' },
            { title: 'face with hand over mouth', emoji: '🤭' },
            { title: 'face with open eyes and hand over mouth', emoji: '🫢' },
            { title: 'face with peeking eye', emoji: '🫣' },
            { title: 'shushing face', emoji: '🤫' },
            { title: 'thinking face', emoji: '🤔' },
            { title: 'saluting face', emoji: '🫡' },
            { title: 'zipper-mouth face', emoji: '🤐' },
            { title: 'face with raised eyebrow', emoji: '🤨' },
            { title: 'neutral face', emoji: '😐' },
            { title: 'expressionless face', emoji: '😑' },
            { title: 'face without mouth', emoji: '😶' },
            { title: 'dotted line face', emoji: '🫥' },
            { title: 'face in clouds', emoji: '😶‍🌫️' },
            { title: 'smirking face', emoji: '😏' },
            { title: 'unamused face', emoji: '😒' },
            { title: 'face with rolling eyes', emoji: '🙄' },
            { title: 'grimacing face', emoji: '😬' },
            { title: 'face exhaling', emoji: '😮‍💨' },
            { title: 'lying face', emoji: '🤥' },
            { title: 'shaking face', emoji: '🫨' },
            { title: 'head shaking horizontally', emoji: '🙂‍↔️' },
            { title: 'head shaking vertically', emoji: '🙂‍↕️' },
            { title: 'relieved face', emoji: '😌' },
            { title: 'pensive face', emoji: '😔' },
            { title: 'sleepy face', emoji: '😪' },
            { title: 'drooling face', emoji: '🤤' },
            { title: 'sleeping face', emoji: '😴' },
            { title: 'face with bags under eyes', emoji: '🫩' },
            { title: 'face with medical mask', emoji: '😷' },
            { title: 'face with thermometer', emoji: '🤒' },
            { title: 'face with head-bandage', emoji: '🤕' },
            { title: 'nauseated face', emoji: '🤢' },
            { title: 'face vomiting', emoji: '🤮' },
            { title: 'sneezing face', emoji: '🤧' },
            { title: 'hot face', emoji: '🥵' },
            { title: 'cold face', emoji: '🥶' },
            { title: 'woozy face', emoji: '🥴' },
            { title: 'face with crossed-out eyes', emoji: '😵' },
            { title: 'face with spiral eyes', emoji: '😵‍💫' },
            { title: 'exploding head', emoji: '🤯' },
            { title: 'cowboy hat face', emoji: '🤠' },
            { title: 'partying face', emoji: '🥳' },
            { title: 'disguised face', emoji: '🥸' },
            { title: 'smiling face with sunglasses', emoji: '😎' },
            { title: 'nerd face', emoji: '🤓' },
            { title: 'face with monocle', emoji: '🧐' },
            { title: 'confused face', emoji: '😕' },
            { title: 'face with diagonal mouth', emoji: '🫤' },
            { title: 'worried face', emoji: '😟' },
            { title: 'slightly frowning face', emoji: '🙁' },
            { title: 'frowning face', emoji: '☹️' },
            { title: 'face with open mouth', emoji: '😮' },
            { title: 'hushed face', emoji: '😯' },
            { title: 'astonished face', emoji: '😲' },
            { title: 'flushed face', emoji: '😳' },
            { title: 'pleading face', emoji: '🥺' },
            { title: 'face holding back tears', emoji: '🥹' },
            { title: 'frowning face with open mouth', emoji: '😦' },
            { title: 'anguished face', emoji: '😧' },
            { title: 'fearful face', emoji: '😨' },
            { title: 'anxious face with sweat', emoji: '😰' },
            { title: 'sad but relieved face', emoji: '😥' },
            { title: 'crying face', emoji: '😢' },
            { title: 'loudly crying face', emoji: '😭' },
            { title: 'face screaming in fear', emoji: '😱' },
            { title: 'confounded face', emoji: '😖' },
            { title: 'persevering face', emoji: '😣' },
            { title: 'disappointed face', emoji: '😞' },
            { title: 'downcast face with sweat', emoji: '😓' },
            { title: 'weary face', emoji: '😩' },
            { title: 'tired face', emoji: '😫' },
            { title: 'yawning face', emoji: '🥱' },
            { title: 'face with steam from nose', emoji: '😤' },
            { title: 'enraged face', emoji: '😡' },
            { title: 'angry face', emoji: '😠' },
            { title: 'face with symbols on mouth', emoji: '🤬' },
            { title: 'smiling face with horns', emoji: '😈' },
            { title: 'angry face with horns', emoji: '👿' },
            { title: 'skull', emoji: '💀' },
            { title: 'skull and crossbones', emoji: '☠️' },
            { title: 'pile of poo', emoji: '💩' },
            { title: 'clown face', emoji: '🤡' },
            { title: 'ogre', emoji: '👹' },
            { title: 'goblin', emoji: '👺' },
            { title: 'ghost', emoji: '👻' },
            { title: 'alien', emoji: '👽' },
            { title: 'alien monster', emoji: '👾' },
            { title: 'robot', emoji: '🤖' },
            { title: 'grinning cat', emoji: '😺' },
            { title: 'grinning cat with smiling eyes', emoji: '😸' },
            { title: 'cat with tears of joy', emoji: '😹' },
            { title: 'smiling cat with heart-eyes', emoji: '😻' },
            { title: 'cat with wry smile', emoji: '😼' },
            { title: 'kissing cat', emoji: '😽' },
            { title: 'weary cat', emoji: '🙀' },
            { title: 'crying cat', emoji: '😿' },
            { title: 'pouting cat', emoji: '😾' },
            { title: 'see-no-evil monkey', emoji: '🙈' },
            { title: 'hear-no-evil monkey', emoji: '🙉' },
            { title: 'speak-no-evil monkey', emoji: '🙊' },
            { title: 'waving hand', emoji: '👋' },
            { title: 'raised back of hand', emoji: '🤚' },
            { title: 'hand with fingers splayed', emoji: '🖐️' },
            { title: 'raised hand', emoji: '✋' },
            { title: 'vulcan salute', emoji: '🖖' },
            { title: 'rightwards hand', emoji: '🫱' },
            { title: 'leftwards hand', emoji: '🫲' },
            { title: 'palm down hand', emoji: '🫳' },
            { title: 'palm up hand', emoji: '🫴' },
            { title: 'leftwards pushing hand', emoji: '🫷' },
            { title: 'rightwards pushing hand', emoji: '🫸' },
            { title: 'OK hand', emoji: '👌' },
            { title: 'pinched fingers', emoji: '🤌' },
            { title: 'pinching hand', emoji: '🤏' },
            { title: 'victory hand', emoji: '✌️' },
            { title: 'crossed fingers', emoji: '🤞' },
            { title: 'hand with index finger and thumb crossed', emoji: '🫰' },
            { title: 'love-you gesture', emoji: '🤟' },
            { title: 'sign of the horns', emoji: '🤘' },
            { title: 'call me hand', emoji: '🤙' },
            { title: 'backhand index pointing left', emoji: '👈' },
            { title: 'backhand index pointing right', emoji: '👉' },
            { title: 'backhand index pointing up', emoji: '👆' },
            { title: 'middle finger', emoji: '🖕' },
            { title: 'backhand index pointing down', emoji: '👇' },
            { title: 'index pointing up', emoji: '☝️' },
            { title: 'index pointing at the viewer', emoji: '🫵' },
            { title: 'thumbs up', emoji: '👍' },
            { title: 'thumbs down', emoji: '👎' },
            { title: 'raised fist', emoji: '✊' },
            { title: 'oncoming fist', emoji: '👊' },
            { title: 'left-facing fist', emoji: '🤛' },
            { title: 'right-facing fist', emoji: '🤜' },
            { title: 'clapping hands', emoji: '👏' },
            { title: 'raising hands', emoji: '🙌' },
            { title: 'heart hands', emoji: '🫶' },
            { title: 'open hands', emoji: '👐' },
            { title: 'palms up together', emoji: '🤲' },
            { title: 'handshake', emoji: '🤝' },
            { title: 'folded hands', emoji: '🙏' },
            { title: 'writing hand', emoji: '✍️' },
            { title: 'nail polish', emoji: '💅' },
            { title: 'selfie', emoji: '🤳' },
            { title: 'flexed biceps', emoji: '💪' },
            { title: 'mechanical arm', emoji: '🦾' },
            { title: 'mechanical leg', emoji: '🦿' },
            { title: 'leg', emoji: '🦵' },
            { title: 'foot', emoji: '🦶' },
            { title: 'ear', emoji: '👂' },
            { title: 'ear with hearing aid', emoji: '🦻' },
            { title: 'nose', emoji: '👃' },
            { title: 'brain', emoji: '🧠' },
            { title: 'anatomical heart', emoji: '🫀' },
            { title: 'lungs', emoji: '🫁' },
            { title: 'tooth', emoji: '🦷' },
            { title: 'bone', emoji: '🦴' },
            { title: 'eyes', emoji: '👀' },
            { title: 'eye', emoji: '👁️' },
            { title: 'tongue', emoji: '👅' },
            { title: 'mouth', emoji: '👄' },
            { title: 'biting lip', emoji: '🫦' },
            { title: "kiss", emoji: " 💋" },
            { title: "couple with heart", emoji: " 💑" },
            { title: "woman and man with heart", emoji: " 👩‍❤️‍👨" },
            { title: "woman and woman with heart", emoji: " 👩‍❤️‍👩" },
            { title: "man and man with heart", emoji: " 👨‍❤️‍👨" },
            { title: 'baby', emoji: '👶' },
            { title: 'child', emoji: '🧒' },
            { title: 'boy', emoji: '👦' },
            { title: 'girl', emoji: '👧' },
            { title: 'person', emoji: '🧑' },
            { title: 'person: blond hair', emoji: '👱' },
            { title: 'man', emoji: '👨' },
            { title: 'person: beard', emoji: '🧔' },
            { title: 'man: beard', emoji: '🧔‍♂️' },
            { title: 'woman: beard', emoji: '🧔‍♀️' },
            { title: 'man: red hair', emoji: '👨‍🦰' },
            { title: 'man: curly hair', emoji: '👨‍🦱' },
            { title: 'man: white hair', emoji: '👨‍🦳' },
            { title: 'man: bald', emoji: '👨‍🦲' },
            { title: 'woman', emoji: '👩' },
            { title: 'woman: red hair', emoji: '👩‍🦰' },
            { title: 'person: red hair', emoji: '🧑‍🦰' },
            { title: 'woman: curly hair', emoji: '👩‍🦱' },
            { title: 'person: curly hair', emoji: '🧑‍🦱' },
            { title: 'woman: white hair', emoji: '👩‍🦳' },
            { title: 'person: white hair', emoji: '🧑‍🦳' },
            { title: 'woman: bald', emoji: '👩‍🦲' },
            { title: 'person: bald', emoji: '🧑‍🦲' },
            { title: 'woman: blond hair', emoji: '👱‍♀️' },
            { title: 'man: blond hair', emoji: '👱‍♂️' },
            { title: 'older person', emoji: '🧓' },
            { title: 'old man', emoji: '👴' },
            { title: 'old woman', emoji: '👵' },
            { title: "person frowning", emoji: "🙍" },
            { title: "man frowning", emoji: "🙍‍♂️" },
            { title: "woman frowning", emoji: "🙍‍♀️" },
            { title: "person pouting", emoji: "🙎" },
            { title: "man pouting", emoji: "🙎‍♂️" },
            { title: "woman pouting", emoji: "🙎‍♀️" },
            { title: "person gesturing NO", emoji: "🙅" },
            { title: "man gesturing NO", emoji: "🙅‍♂️" },
            { title: "woman gesturing NO", emoji: "🙅‍♀️" },
            { title: "person gesturing OK", emoji: "🙆" },
            { title: "man gesturing OK", emoji: "🙆‍♂️" },
            { title: "woman gesturing OK", emoji: "🙆‍♀️" },
            { title: "person tipping hand", emoji: "💁" },
            { title: "man tipping hand", emoji: "💁‍♂️" },
            { title: "woman tipping hand", emoji: "💁‍♀️" },
            { title: "person raising hand", emoji: "🙋" },
            { title: "man raising hand", emoji: "🙋‍♂️" },
            { title: "woman raising hand", emoji: "🙋‍♀️" },
            { title: "deaf person", emoji: "🧏" },
            { title: "deaf man", emoji: "🧏‍♂️" },
            { title: "deaf woman", emoji: "🧏‍♀️" },
            { title: "person bowing", emoji: "🙇" },
            { title: "man bowing", emoji: "🙇‍♂️" },
            { title: "woman bowing", emoji: "🙇‍♀️" },
            { title: "person facepalming", emoji: "🤦" },
            { title: "man facepalming", emoji: "🤦‍♂️" },
            { title: "woman facepalming", emoji: "🤦‍♀️" },
            { title: "person shrugging", emoji: "🤷" },
            { title: "man shrugging", emoji: "🤷‍♂️" },
            { title: "woman shrugging", emoji: "🤷‍♀️" },
            { title: "health worker", emoji: "🧑‍⚕️" },
            { title: "man health worker", emoji: "👨‍⚕️" },
            { title: "woman health worker", emoji: "👩‍⚕️" },
            { title: "student", emoji: "🧑‍🎓" },
            { title: "man student", emoji: "👨‍🎓" },
            { title: "woman student", emoji: "👩‍🎓" },
            { title: "teacher", emoji: "🧑‍🏫" },
            { title: "man teacher", emoji: "👨‍🏫" },
            { title: "woman teacher", emoji: "👩‍🏫" },
            { title: "judge", emoji: "🧑‍⚖️" },
            { title: "man judge", emoji: "👨‍⚖️" },
            { title: "woman judge", emoji: "👩‍⚖️" },
            { title: "farmer", emoji: "🧑‍🌾" },
            { title: "man farmer", emoji: "👨‍🌾" },
            { title: "woman farmer", emoji: "👩‍🌾" },
            { title: "cook", emoji: "🧑‍🍳" },
            { title: "man cook", emoji: "👨‍🍳" },
            { title: "woman cook", emoji: "👩‍🍳" },
            { title: "mechanic", emoji: "🧑‍🔧" },
            { title: "man mechanic", emoji: "👨‍🔧" },
            { title: "woman mechanic", emoji: "👩‍🔧" },
            { title: "factory worker", emoji: "🧑‍🏭" },
            { title: "man factory worker", emoji: "👨‍🏭" },
            { title: "woman factory worker", emoji: "👩‍🏭" },
            { title: "office worker", emoji: "🧑‍💼" },
            { title: "man office worker", emoji: "👨‍💼" },
            { title: "woman office worker", emoji: "👩‍💼" },
            { title: "scientist", emoji: "🧑‍🔬" },
            { title: "man scientist", emoji: "👨‍🔬" },
            { title: "woman scientist", emoji: "👩‍🔬" },
            { title: "artist", emoji: "🧑‍🎨" },
            { title: "man artist", emoji: "👨‍🎨" },
            { title: "woman artist", emoji: "👩‍🎨" },
            { title: "firefighter", emoji: "🧑‍🚒" },
            { title: "man firefighter", emoji: "👨‍🚒" },
            { title: "woman firefighter", emoji: "👩‍🚒" },
            { title: "pilot", emoji: "🧑‍✈️" },
            { title: "man pilot", emoji: "👨‍✈️" },
            { title: "woman pilot", emoji: "👩‍✈️" },
            { title: "astronaut", emoji: "🧑‍🚀" },
            { title: "man astronaut", emoji: "👨‍🚀" },
            { title: "woman astronaut", emoji: "👩‍🚀" },
            { title: "person in suit", emoji: "🤵" },
            { title: "man in suit", emoji: "🤵‍♂️" },
            { title: "woman in suit", emoji: "🤵‍♀️" },
            { title: "prince", emoji: "🤴" },
            { title: "princess", emoji: "👸" },
            { title: "person with turban", emoji: "👳" },
            { title: "man with turban", emoji: "👳‍♂️" },
            { title: "woman with turban", emoji: "👳‍♀️" },
            { title: "person with skullcap", emoji: "👲" },
            { title: "woman with headscarf", emoji: "🧕" },
            { title: "person in tuxedo", emoji: "🤵" },
            { title: "bride with veil", emoji: "👰‍♀️" },
            { title: "man in veil", emoji: "👰‍♂️" },
            { title: "pregnant person", emoji: "🫄" },
            { title: "pregnant man", emoji: "🫃" },
            { title: "pregnant woman", emoji: "🤰" },
            { title: "breast-feeding", emoji: "🤱" },
            { title: "woman feeding baby", emoji: "👩‍🍼" },
            { title: "man feeding baby", emoji: "👨‍🍼" },
            { title: "person feeding baby", emoji: "🧑‍🍼" },
            { title: "baby angel", emoji: "👼" },
            { title: "Santa Claus", emoji: "🎅" },
            { title: "Mrs. Claus", emoji: "🤶" },
            { title: "mx claus", emoji: "🧑‍🎄" },
            { title: "superhero", emoji: "🦸" },
            { title: "man superhero", emoji: "🦸‍♂️" },
            { title: "woman superhero", emoji: "🦸‍♀️" },
            { title: "supervillain", emoji: "🦹" },
            { title: "man supervillain", emoji: "🦹‍♂️" },
            { title: "woman supervillain", emoji: "🦹‍♀️" },
            { title: "mage", emoji: "🧙" },
            { title: "man mage", emoji: "🧙‍♂️" },
            { title: "woman mage", emoji: "🧙‍♀️" },
            { title: "fairy", emoji: "🧚" },
            { title: "man fairy", emoji: "🧚‍♂️" },
            { title: "woman fairy", emoji: "🧚‍♀️" },
            { title: "vampire", emoji: "🧛" },
            { title: "man vampire", emoji: "🧛‍♂️" },
            { title: "woman vampire", emoji: "🧛‍♀️" },
            { title: "merperson", emoji: "🧜" },
            { title: "merman", emoji: "🧜‍♂️" },
            { title: "mermaid", emoji: "🧜‍♀️" },
            { title: "elf", emoji: "🧝" },
            { title: "man elf", emoji: "🧝‍♂️" },
            { title: "woman elf", emoji: "🧝‍♀️" },
            { title: "genie", emoji: "🧞" },
            { title: "man genie", emoji: "🧞‍♂️" },
            { title: "woman genie", emoji: "🧞‍♀️" },
            { title: "zombie", emoji: "🧟" },
            { title: "man zombie", emoji: "🧟‍♂️" },
            { title: "woman zombie", emoji: "🧟‍♀️" },
            { title: "person getting massage", emoji: "💆" },
            { title: "man getting massage", emoji: "💆‍♂️" },
            { title: "woman getting massage", emoji: "💆‍♀️" },
            { title: "person getting haircut", emoji: "💇" },
            { title: "man getting haircut", emoji: "💇‍♂️" },
            { title: "woman getting haircut", emoji: "💇‍♀️" },
            { title: "person walking", emoji: "🚶" },
            { title: "man walking", emoji: "🚶‍♂️" },
            { title: "woman walking", emoji: "🚶‍♀️" },
            { title: "person standing", emoji: "🧍" },
            { title: "man standing", emoji: "🧍‍♂️" },
            { title: "woman standing", emoji: "🧍‍♀️" },
            { title: "person with cane", emoji: "🧑‍🦯" },
            { title: "man with cane", emoji: "👨‍🦯" },
            { title: "woman with cane", emoji: "👩‍🦯" },
            { title: "person in manual wheelchair", emoji: "🧑‍🦼" },
            { title: "man in manual wheelchair", emoji: "👨‍🦼" },
            { title: "woman in manual wheelchair", emoji: "👩‍🦼" },
            { title: "person in motorized wheelchair", emoji: "🧑‍🦽" },
            { title: "man in motorized wheelchair", emoji: "👨‍🦽" },
            { title: "woman in motorized wheelchair", emoji: "👩‍🦽" },
            { title: "person running", emoji: "🏃" },
            { title: "man running", emoji: "🏃‍♂️" },
            { title: "woman running", emoji: "🏃‍♀️" },
            { title: "woman dancing", emoji: "💃" },
            { title: "man dancing", emoji: "🕺" },
            { title: "person in lotus position", emoji: "🧘" },
            { title: "man in lotus position", emoji: "🧘‍♂️" },
            { title: "woman in lotus position", emoji: "🧘‍♀️" },
            { title: "people holding hands", emoji: "🧑‍🤝‍🧑" },
            { title: "women holding hands", emoji: "👭" },
            { title: "woman and man holding hands", emoji: "👫" },
            { title: "men holding hands", emoji: "👬" },
            { title: "family", emoji: " 👪" },
            { title: "family: man, woman, boy", emoji: " 👨‍👩‍👦" },
            { title: "family: man, woman, girl", emoji: " 👨‍👩‍👧" },
            { title: "family: man, woman, girl, boy", emoji: " 👨‍👩‍👧‍👦" },
            { title: "family: man, woman, boy, boy", emoji: " 👨‍👩‍👦‍👦" },
            { title: "family: man, woman, girl, girl", emoji: " 👨‍👩‍👧‍👧" },
            { title: "family: man, man, boy", emoji: " 👨‍👨‍👦" },
            { title: "family: man, man, girl", emoji: " 👨‍👨‍👧" },
            { title: "family: man, man, girl, boy", emoji: " 👨‍👨‍👧‍👦" },
            { title: "family: man, man, boy, boy", emoji: " 👨‍👨‍👦‍👦" },
            { title: "family: man, man, girl, girl", emoji: " 👨‍👨‍👧‍👧" },
            { title: "family: woman, woman, boy", emoji: " 👩‍👩‍👦" },
            { title: "family: woman, woman, girl", emoji: " 👩‍👩‍👧" },
            { title: "family: woman, woman, girl, boy", emoji: " 👩‍👩‍👧‍👦" },
            { title: "family: woman, woman, boy, boy", emoji: " 👩‍👩‍👦‍👦" },
            { title: "family: woman, woman, girl, girl", emoji: " 👩‍👩‍👧‍👧" },
            { title: "family: woman, boy", emoji: " 👩‍👦" },
            { title: "family: woman, girl", emoji: " 👩‍👧" },
            { title: "family: woman, girl, boy", emoji: " 👩‍👧‍👦" },
            { title: "family: woman, boy, boy", emoji: " 👩‍👦‍👦" },
            { title: "family: woman, girl, girl", emoji: " 👩‍👧‍👧" },
            { title: "family: man, boy", emoji: " 👨‍👦" },
            { title: "family: man, girl", emoji: " 👨‍👧" },
            { title: "family: man, girl, boy", emoji: " 👨‍👧‍👦" },
            { title: "family: man, boy, boy", emoji: " 👨‍👦‍👦" },
            { title: "family: man, girl, girl", emoji: " 👨‍👧‍👧" },
            { title: "coat", emoji: "🧥" },
            { title: "lab coat", emoji: "🥼" },
            { title: "safety vest", emoji: "🦺" },
            { title: "dress", emoji: "👗" },
            { title: "bikini", emoji: "👙" },
            { title: "one-piece swimsuit", emoji: "🩱" },
            { title: "briefs", emoji: "🩲" },
            { title: "shorts", emoji: "🩳" },
            { title: "jeans", emoji: "👖" },
            { title: "scarf", emoji: "🧣" },
            { title: "gloves", emoji: "🧤" },
            { title: "socks", emoji: "🧦" },
            { title: "running shoe", emoji: "👟" },
            { title: "flat shoe", emoji: "🩰" },
            { title: "high-heeled shoe", emoji: "👠" },
            { title: "woman’s sandal", emoji: "👡" },
            { title: "boot", emoji: "👢" },
            { title: "slipper", emoji: "🩴" },
            { title: "thong sandal", emoji: "🩴" },
            { title: "hiking boot", emoji: "🥾" },
            { title: "crown", emoji: "👑" },
            { title: "woman’s hat", emoji: "👒" },
            { title: "top hat", emoji: "🎩" },
            { title: "graduation cap", emoji: "🎓" },
            { title: "billed cap", emoji: "🧢" },
            { title: "military helmet", emoji: "🪖" },
            { title: "rescue worker’s helmet", emoji: "⛑️" },
            { title: "prayer beads", emoji: "📿" },
            { title: "lipstick", emoji: "💄" },
            { title: "ring", emoji: "💍" },
            { title: "gem stone", emoji: "💎" }
        ]
    },
    {
        id: '3',
        category: 'Animals & Nature',
        icon: EmojiNatureOutlined,
        emojis: [
            { title: "dog", emoji: "🐶" },
            { title: "cat", emoji: "🐱" },
            { title: "mouse", emoji: "🐭" },
            { title: "hamster", emoji: "🐹" },
            { title: "rabbit", emoji: "🐰" },
            { title: "fox", emoji: "🦊" },
            { title: "bear", emoji: "🐻" },
            { title: "panda", emoji: "🐼" },
            { title: "polar bear", emoji: "🐻‍❄️" },
            { title: "koala", emoji: "🐨" },
            { title: "tiger", emoji: "🐯" },
            { title: "lion", emoji: "🦁" },
            { title: "cow", emoji: "🐮" },
            { title: "pig face", emoji: "🐷" },
            { title: "pig nose", emoji: "🐽" },
            { title: "frog", emoji: "🐸" },
            { title: "monkey", emoji: "🐵" },
            { title: "see-no-evil monkey", emoji: "🙈" },
            { title: "hear-no-evil monkey", emoji: "🙉" },
            { title: "speak-no-evil monkey", emoji: "🙊" },
            { title: "monkey", emoji: "🐒" },
            { title: "chicken", emoji: "🐔" },
            { title: "penguin", emoji: "🐧" },
            { title: "bird", emoji: "🐦" },
            { title: "baby chick", emoji: "🐤" },
            { title: "hatching chick", emoji: "🐣" },
            { title: "front-facing baby chick", emoji: "🐥" },
            { title: "goose", emoji: "🪿" },
            { title: "duck", emoji: "🦆" },
            { title: "black bird", emoji: "🐦‍⬛" },
            { title: "eagle", emoji: "🦅" },
            { title: "owl", emoji: "🦉" },
            { title: "bat", emoji: "🦇" },
            { title: "wolf", emoji: "🐺" },
            { title: "boar", emoji: "🐗" },
            { title: "horse", emoji: "🐴" },
            { title: "unicorn", emoji: "🦄" },
            { title: "moose", emoji: "🫎" },
            { title: "honeybee", emoji: "🐝" },
            { title: "worm", emoji: "🪱" },
            { title: "bug", emoji: "🐛" },
            { title: "butterfly", emoji: "🦋" },
            { title: "snail", emoji: "🐌" },
            { title: "lady beetle", emoji: "🐞" },
            { title: "ant", emoji: "🐜" },
            { title: "fly", emoji: "🪰" },
            { title: "beetle", emoji: "🪲" },
            { title: "cockroach", emoji: "🪳" },
            { title: "squid", emoji: "🦑" },
            { title: "octopus", emoji: "🐙" },
            { title: "sauropod", emoji: "🦕" },
            { title: "t-rex", emoji: "🦖" },
            { title: "lizard", emoji: "🦎" },
            { title: "snake", emoji: "🐍" },
            { title: "turtle", emoji: "🐢" },
            { title: "scorpion", emoji: "🦂" },
            { title: "spider web", emoji: "🕸️" },
            { title: "spider", emoji: "🕷️" },
            { title: "cricket", emoji: "🦗" },
            { title: "mosquito", emoji: "🦟" },
            { title: "jellyfish", emoji: "🪼" },
            { title: "shrimp", emoji: "🦐" },
            { title: "lobster", emoji: "🦞" },
            { title: "crab", emoji: "🦀" },
            { title: "blowfish", emoji: "🐡" },
            { title: "tropical fish", emoji: "🐠" },
            { title: "fish", emoji: "🐟" },
            { title: "dolphin", emoji: "🐬" },
            { title: "spouting whale", emoji: "🐳" },
            { title: "whale", emoji: "🐋" },
            { title: "shark", emoji: "🦈" },
            { title: "seal", emoji: "🦭" },
            { title: "two-hump camel", emoji: "🐫" },
            { title: "camel", emoji: "🐪" },
            { title: "rhinoceros", emoji: "🦏" },
            { title: "hippopotamus", emoji: "🦛" },
            { title: "elephant", emoji: "🐘" },
            { title: "mammoth", emoji: "🦣" },
            { title: "orangutan", emoji: "🦧" },
            { title: "gorilla", emoji: "🦍" },
            { title: "zebra", emoji: "🦓" },
            { title: "leopard", emoji: "🐆" },
            { title: "tiger", emoji: "🐅" },
            { title: "crocodile", emoji: "🐊" },
            { title: "giraffe", emoji: "🦒" },
            { title: "kangaroo", emoji: "🦘" },
            { title: "bison", emoji: "🦬" },
            { title: "water buffalo", emoji: "🐃" },
            { title: "ox", emoji: "🐂" },
            { title: "cow", emoji: "🐄" },
            { title: "donkey", emoji: "🫏" },
            { title: "horse", emoji: "🐎" },
            { title: "pig", emoji: "🐖" },
            { title: "ram", emoji: "🐏" },
            { title: "ewe", emoji: "🐑" },
            { title: "llama", emoji: "🦙" },
            { title: "turkey", emoji: "🦃" },
            { title: "rooster", emoji: "🐓" },
            { title: "wing", emoji: "🪽" },
            { title: "feather", emoji: "🪶" },
            { title: "black cat", emoji: "🐈‍⬛" },
            { title: "cat", emoji: "🐈" },
            { title: "service dog", emoji: "🐕‍🦺" },
            { title: "guide dog", emoji: "🦮" },
            { title: "poodle", emoji: "🐩" },
            { title: "dog", emoji: "🐕" },
            { title: "deer", emoji: "🦌" },
            { title: "goat", emoji: "🐐" },
            { title: "dodo", emoji: "🦤" },
            { title: "peacock", emoji: "🦚" },
            { title: "parrot", emoji: "🦜" },
            { title: "swan", emoji: "🦢" },
            { title: "flamingo", emoji: "🦩" },
            { title: "dove", emoji: "🕊️" },
            { title: "rabbit", emoji: "🐇" },
            { title: "raccoon", emoji: "🦝" },
            { title: "skunk", emoji: "🦨" },
            { title: "badger", emoji: "🦡" },
            { title: "beaver", emoji: "🦫" },
            { title: "otter", emoji: "🦦" },
            { title: "evergreen tree", emoji: "🌲" },
            { title: "christmas tree", emoji: "🎄" },
            { title: "cactus", emoji: "🌵" },
            { title: "phoenix", emoji: "🐦‍🔥" },
            { title: "dragon", emoji: "🐲" },
            { title: "dragon", emoji: "🐉" },
            { title: "paw prints", emoji: "🐾" },
            { title: "hedgehog", emoji: "🦔" },
            { title: "chipmunk", emoji: "🐿️" },
            { title: "rat", emoji: "🐀" },
            { title: "mouse", emoji: "🐁" },
            { title: "sloth", emoji: "🦥" },
            { title: "deciduous tree", emoji: "🌳" },
            { title: "palm tree", emoji: "🌴" },
            { title: "wood", emoji: "🪵" },
            { title: "seedling", emoji: "🌱" },
            { title: "herb", emoji: "🌿" },
            { title: "shamrock", emoji: "☘️" },
            { title: "four leaf clover", emoji: "🍀" },
            { title: "pine decoration", emoji: "🎍" },
            { title: "potted plant", emoji: "🪴" },
            { title: "bamboo", emoji: "🎋" },
            { title: "leaf fluttering in wind", emoji: "🍃" },
            { title: "fallen leaf", emoji: "🍂" },
            { title: "rose", emoji: "🌹" },
            { title: "tulip", emoji: "🌷" },
            { title: "bouquet", emoji: "💐" },
            { title: "sheaf of rice", emoji: "🌾" },
            { title: "rock", emoji: "🪨" },
            { title: "coral", emoji: "🪸" },
            { title: "spiral shell", emoji: "🐚" },
            { title: "brown mushroom", emoji: "🍄‍🟫" },
            { title: "mushroom", emoji: "🍄" },
            { title: "empty nest", emoji: "🪹" },
            { title: "nest with eggs", emoji: "🪺" },
            { title: "maple leaf", emoji: "🍁" },
            { title: "wilted flower", emoji: "🥀" },
            { title: "hyacinth", emoji: "🪻" },
            { title: "lotus", emoji: "🪷" },
            { title: "hibiscus", emoji: "🌺" },
            { title: "cherry blossom", emoji: "🌸" },
            { title: "blossom", emoji: "🌼" },
            { title: "sunflower", emoji: "🌻" },
            { title: "sun with face", emoji: "🌞" },
            { title: "full moon with face", emoji: "🌝" },
            { title: "first quarter moon with face", emoji: "🌛" },
            { title: "last quarter moon with face", emoji: "🌜" },
            { title: "new moon with face", emoji: "🌚" },
            { title: "globe showing asia-australia", emoji: "🌏" },
            { title: "globe showing europe-africa", emoji: "🌍" },
            { title: "globe showing americas", emoji: "🌎" },
            { title: "crescent moon", emoji: "🌙" },
            { title: "waxing gibbous moon", emoji: "🌔" },
            { title: "first quarter moon", emoji: "🌓" },
            { title: "waxing crescent moon", emoji: "🌒" },
            { title: "new moon", emoji: "🌑" },
            { title: "waning crescent moon", emoji: "🌘" },
            { title: "last quarter moon", emoji: "🌗" },
            { title: "waning gibbous moon", emoji: "🌖" },
            { title: "full moon", emoji: "🌕" },
            { title: "ringed planet", emoji: "🪐" },
            { title: "dizzy", emoji: "💫" },
            { title: "star", emoji: "⭐" },
            { title: "glowing star", emoji: "🌟" },
            { title: "sparkles", emoji: "✨" },
            { title: "high voltage", emoji: "⚡" },
            { title: "comet", emoji: "☄️" },
            { title: "collision", emoji: "💥" },
            { title: "fire", emoji: "🔥" },
            { title: "tornado", emoji: "🌪️" },
            { title: "rainbow", emoji: "🌈" },
            { title: "sun", emoji: "☀️" },
            { title: "snowman without snow", emoji: "⛄" },
            { title: "snowman", emoji: "☃️" },
            { title: "snowflake", emoji: "❄️" },
            { title: "cloud with snow", emoji: "🌨️" },
            { title: "cloud with lightning and rain", emoji: "🌩️" },
            { title: "cloud with rain", emoji: "🌧️" },
            { title: "sun behind cloud with rain", emoji: "🌦️" },
            { title: "cloud", emoji: "☁️" },
            { title: "sun behind large cloud", emoji: "🌥️" },
            { title: "sun behind cloud", emoji: "⛅" },
            { title: "sun behind small cloud", emoji: "🌤️" },
            { title: "wind face", emoji: "🌬️" },
            { title: "dashing away", emoji: "💨" },
            { title: "drop", emoji: "💧" },
            { title: "splashing sweat symbol", emoji: "💦" },
            { title: "bubbles", emoji: "🫧" },
            { title: "umbrella with rain drops", emoji: "☔" },
            { title: "umbrella", emoji: "☂️" },
            { title: "water wave", emoji: "🌊" },
            { title: "fog", emoji: "🌫️" }
        ]
    },
    {
        id: '4',
        category: 'Food & Drink',
        icon: EmojiFoodBeverageOutlined,
        emojis: [
            { title: "red apple", emoji: "🍎" },
            { title: "green apple", emoji: "🍏" },
            { title: "pear", emoji: "🍐" },
            { title: "tangerine", emoji: "🍊" },
            { title: "lemon", emoji: "🍋" },
            { title: "banana", emoji: "🍌" },
            { title: "watermelon", emoji: "🍉" },
            { title: "grapes", emoji: "🍇" },
            { title: "strawberry", emoji: "🍓" },
            { title: "blueberry", emoji: "🫐" },
            { title: "melon", emoji: "🍈" },
            { title: "cherry", emoji: "🍒" },
            { title: "peach", emoji: "🍑" },
            { title: "mango", emoji: "🥭" },
            { title: "pineapple", emoji: "🍍" },
            { title: "coconut", emoji: "🥥" },
            { title: "kiwi fruit", emoji: "🥝" },
            { title: "tomato", emoji: "🍅" },
            { title: "aubergine", emoji: "🍆" },
            { title: "avocado", emoji: "🥑" },
            { title: "broccoli", emoji: "🥦" },
            { title: "leafy green", emoji: "🥬" },
            { title: "mushroom", emoji: "🍄" },
            { title: "pepper", emoji: "🫑" },
            { title: "carrot", emoji: "🥕" },
            { title: "onion", emoji: "🧅" },
            { title: "potato", emoji: "🥔" },
            { title: "sweet potato", emoji: "🍠" },
            { title: "croissant", emoji: "🥐" },
            { title: "bagel", emoji: "🥯" },
            { title: "bread", emoji: "🍞" },
            { title: "baguette bread", emoji: "🥖" },
            { title: "pretzels", emoji: "🥨" },
            { title: "butter", emoji: "🧈" },
            { title: "cheese wedge", emoji: "🧀" },
            { title: "egg", emoji: "🥚" },
            { title: "cooking", emoji: "🍳" },
            { title: "shallow pan of food", emoji: "🥘" },
            { title: "pot of food", emoji: "🍲" },
            { title: "fondue", emoji: "🫕" },
            { title: "bowl with spoon", emoji: "🥣" },
            { title: "green salad", emoji: "🥗" },
            { title: "popcorn", emoji: "🍿" },
            { title: "steamed rice", emoji: "🍚" },
            { title: "cooked rice", emoji: "🍙" },
            { title: "rice cracker", emoji: "🍘" },
            { title: "curry rice", emoji: "🍛" },
            { title: "dango", emoji: "🍡" },
            { title: "oden", emoji: "🍢" },
            { title: "sushi", emoji: "🍣" },
            { title: "tempura", emoji: "🍤" },
            { title: "fish cake with swirl", emoji: "🍥" },
            { title: "moon cake", emoji: "🥮" },
            { title: "dumpling", emoji: "🥟" },
            { title: "fortune cookie", emoji: "🥠" },
            { title: "canned food", emoji: "🥫" },
            { title: "bento box", emoji: "🍱" },
            { title: "noodle", emoji: "🍜" },
            { title: "steaming bowl", emoji: "🍜" },
            { title: "spaghetti", emoji: "🍝" },
            { title: "french fries", emoji: "🍟" },
            { title: "taco", emoji: "🌮" },
            { title: "burrito", emoji: "🌯" },
            { title: "tamale", emoji: "🫔" },
            { title: "pizza", emoji: "🍕" },
            { title: "hot dog", emoji: "🌭" },
            { title: "sandwich", emoji: "🥪" },
            { title: "stuffed flatbread", emoji: "🥙" },
            { title: "falafel", emoji: "🧆" },
            { title: "kebab", emoji: "🫓" },
            { title: "pie", emoji: "🥧" },
            { title: "chopsticks", emoji: "🥢" },
            { title: "fork and knife with plate", emoji: "🍽️" },
            { title: "fork and knife", emoji: "🍴" },
            { title: "spoon", emoji: "🥄" },
            { title: "soy sauce", emoji: "🍶" },
            { title: "cut of meat", emoji: "🥩" },
            { title: "poultry leg", emoji: "🍗" },
            { title: "roasted meat", emoji: "🍖" },
            { title: "fish", emoji: "🐟" },
            { title: "tropical fish", emoji: "🐠" },
            { title: "blowfish", emoji: "🐡" },
            { title: "shrimp", emoji: "🦐" },
            { title: "lobster", emoji: "🦞" },
            { title: "crab", emoji: "🦀" },
            { title: "octopus", emoji: "🐙" },
            { title: "squid", emoji: "🦑" },
            { title: "birthday cake", emoji: "🎂" },
            { title: "shortcake", emoji: "🍰" },
            { title: "cupcake", emoji: "🧁" },
            { title: "chocolate bar", emoji: "🍫" },
            { title: "candy", emoji: "🍬" },
            { title: "lollipop", emoji: "🍭" },
            { title: "custard", emoji: "🍮" },
            { title: "honey pot", emoji: "🍯" },
            { title: "donut", emoji: "🍩" },
            { title: "cookie", emoji: "🍪" },
            { title: "ice cream", emoji: "🍦" },
            { title: "shaved ice", emoji: "🍧" },
            { title: "ice cream sandwich", emoji: "🍨" },
            { title: "soft ice cream", emoji: "🍦" },
            { title: "waffle", emoji: "🧇" },
            { title: "pancake", emoji: "🥞" },
            { title: "hot beverage", emoji: "☕" },
            { title: "tea", emoji: "🍵" },
            { title: "sake", emoji: "🍶" },
            { title: "wine glass", emoji: "🍷" },
            { title: "cocktail glass", emoji: "🍸" },
            { title: "tropical drink", emoji: "🍹" },
            { title: "beer mug", emoji: "🍺" },
            { title: "clinking beer mugs", emoji: "🍻" },
            { title: "clinking glasses", emoji: "🥂" },
            { title: "tumbler glass", emoji: "🥃" },
            { title: "cup with straw", emoji: "🥤" },
            { title: "beverage box", emoji: "🧃" },
            { title: "mate", emoji: "🧉" },
            { title: "bubble tea", emoji: "🧋" },
            { title: "glass of milk", emoji: "🥛" },
            { title: "bottle with popping cork", emoji: "🍾" },
            { title: "take-out box", emoji: "🥡" }
        ]
    },
    {
        id: '5',
        category: 'Activity',
        icon: SportsBaseballOutlined,
        emojis: [
            { title: "soccer ball", emoji: "⚽" },
            { title: "basketball", emoji: "🏀" },
            { title: "american football", emoji: "🏈" },
            { title: "baseball", emoji: "⚾" },
            { title: "softball", emoji: "🥎" },
            { title: "tennis", emoji: "🎾" },
            { title: "volleyball", emoji: "🏐" },
            { title: "rugby football", emoji: "🏉" },
            { title: "flying disc", emoji: "🥏" },
            { title: "8 ball", emoji: "🎱" },
            { title: "yo-yo", emoji: "🪀" },
            { title: "ping pong", emoji: "🏓" },
            { title: "badminton", emoji: "🏸" },
            { title: "ice hockey", emoji: "🏒" },
            { title: "field hockey", emoji: "🏑" },
            { title: "lacrosse", emoji: "🥍" },
            { title: "cricket game", emoji: "🏏" },
            { title: "goal net", emoji: "🥅" },
            { title: "golf", emoji: "⛳" },
            { title: "kite", emoji: "🪁" },
            { title: "bow and arrow", emoji: "🏹" },
            { title: "fishing pole", emoji: "🎣" },
            { title: "boxing glove", emoji: "🥊" },
            { title: "martial arts uniform", emoji: "🥋" },
            { title: "running shirt", emoji: "🎽" },
            { title: "skateboard", emoji: "🛹" },
            { title: "sled", emoji: "🛷" },
            { title: "ice skate", emoji: "⛸️" },
            { title: "curling stone", emoji: "🥌" },
            { title: "ski", emoji: "🎿" },
            { title: "skier", emoji: "⛷️" },
            { title: "snowboarder", emoji: "🏂" },
            { title: "parachute", emoji: "🪂" },
            { title: "person lifting weights", emoji: "🏋️" },
            { title: "man lifting weights", emoji: "🏋️‍♂️" },
            { title: "woman lifting weights", emoji: "🏋️‍♀️" },
            { title: "person biking", emoji: "🚴" },
            { title: "man biking", emoji: "🚴‍♂️" },
            { title: "woman biking", emoji: "🚴‍♀️" },
            { title: "person mountain biking", emoji: "🚵" },
            { title: "man mountain biking", emoji: "🚵‍♂️" },
            { title: "woman mountain biking", emoji: "🚵‍♀️" },
            { title: "person cartwheeling", emoji: "🤸" },
            { title: "man cartwheeling", emoji: "🤸‍♂️" },
            { title: "woman cartwheeling", emoji: "🤸‍♀️" },
            { title: "person playing water polo", emoji: "🤽" },
            { title: "man playing water polo", emoji: "🤽‍♂️" },
            { title: "woman playing water polo", emoji: "🤽‍♀️" },
            { title: "person playing handball", emoji: "🤾" },
            { title: "man playing handball", emoji: "🤾‍♂️" },
            { title: "woman playing handball", emoji: "🤾‍♀️" },
            { title: "person juggling", emoji: "🤹" },
            { title: "man juggling", emoji: "🤹‍♂️" },
            { title: "woman juggling", emoji: "🤹‍♀️" },
            { title: "person fencing", emoji: "🤺" },
            { title: "person in motorized wheelchair", emoji: "🧑‍🦽" },
            { title: "man in motorized wheelchair", emoji: "👨‍🦽" },
            { title: "woman in motorized wheelchair", emoji: "👩‍🦽" },
            { title: "person in manual wheelchair", emoji: "🧑‍🦼" },
            { title: "man in manual wheelchair", emoji: "👨‍🦼" },
            { title: "woman in manual wheelchair", emoji: "👩‍🦼" },
            { title: "person golfing", emoji: "🏌️" },
            { title: "man golfing", emoji: "🏌️‍♂️" },
            { title: "woman golfing", emoji: "🏌️‍♀️" },
            { title: "person horseback riding", emoji: "🏇" },
            { title: "person swimming", emoji: "🏊" },
            { title: "man swimming", emoji: "🏊‍♂️" },
            { title: "woman swimming", emoji: "🏊‍♀️" },
            { title: "person surfing", emoji: "🏄" },
            { title: "man surfing", emoji: "🏄‍♂️" },
            { title: "woman surfing", emoji: "🏄‍♀️" },
            { title: "person rowing boat", emoji: "🚣" },
            { title: "man rowing boat", emoji: "🚣‍♂️" },
            { title: "woman rowing boat", emoji: "🚣‍♀️" },
            { title: "person competing", emoji: "ette" },
            { title: "man competing", emoji: "🤼‍♂️" },
            { title: "woman competing", emoji: "🤼‍♀️" },
            { title: "person doing gymnastics", emoji: "🤸" },
            { title: "person playing musical instrument", emoji: "🧑‍🎤" },
            { title: "man singer", emoji: "👨‍🎤" },
            { title: "woman singer", emoji: "👩‍🎤" },
            { title: "person doing meditation", emoji: "🧘" },
            { title: "man doing meditation", emoji: "🧘‍♂️" },
            { title: "woman doing meditation", emoji: "🧘‍♀️" },
            { title: "artist", emoji: "🧑‍🎨" },
            { title: "man artist", emoji: "👨‍🎨" },
            { title: "woman artist", emoji: "👩‍🎨" },
            { title: "circus tent", emoji: "🎪" },
            { title: "ticket", emoji: "🎫" },
            { title: "clapper board", emoji: "🎬" },
            { title: "performing arts", emoji: "🎭" },
            { title: "artist palette", emoji: "🎨" },
            { title: "test tube", emoji: "🧪" },
            { title: "dna", emoji: "🧬" },
            { title: "microscope", emoji: "🔬" },
            { title: "telescope", emoji: "🔭" },
            { title: "satellite antenna", emoji: "📡" },
            { title: "syringe", emoji: "💉" },
            { title: "pill", emoji: "💊" },
            { title: "kiss mark", emoji: "💋" },
            { title: "love letter", emoji: "💌" },
            { title: "ring", emoji: "💍" },
            { title: "gem stone", emoji: "💎" },
            { title: "ballet shoes", emoji: "🩰" },
            { title: "high-heeled shoe", emoji: "👠" },
            { title: "woman’s sandal", emoji: "👡" },
            { title: "boot", emoji: "👢" },
            { title: "t-shirt", emoji: "👕" },
            { title: "safety vest", emoji: "🦺" },
            { title: "shorts", emoji: "🩳" },
            { title: "dress", emoji: "👗" },
            { title: "kimono", emoji: "👘" },
            { title: "sari", emoji: "🥻" },
            { title: "one-piece swimsuit", emoji: "🩱" },
            { title: "briefs", emoji: "🩲" },
            { title: "bikini", emoji: "👙" },
            { title: "woman’s clothes", emoji: "👚" },
            { title: "purse", emoji: "👛" },
            { title: "handbag", emoji: "👜" },
            { title: "clutch bag", emoji: "👝" },
            { title: "shopping bags", emoji: "🛍️" },
            { title: "backpack", emoji: "🎒" },
            { title: "military helmet", emoji: "🪖" },
            { title: "top hat", emoji: "🎩" },
            { title: "graduation cap", emoji: "🎓" },
            { title: "billed cap", emoji: "🧢" },
            { title: "crown", emoji: "👑" },
            { title: "woman’s hat", emoji: "👒" },
            { title: "headphones", emoji: "🎧" },
            { title: "earmuffs", emoji: "🦺" },
            { title: "closed umbrella", emoji: "🌂" },
            { title: "umbrella", emoji: "☂️" },
            { title: "briefcase", emoji: "💼" },
            { title: "key", emoji: "🔑" },
            { title: "old key", emoji: "🗝️" },
            { title: "bell", emoji: "🔔" },
            { title: "sleigh", emoji: "🛷" },
            { title: "dice", emoji: "🎲" },
            { title: "playing card black joker", emoji: "🃏" },
            { title: "mahjong red dragon", emoji: "🀄" },
            { title: "flower playing cards", emoji: "🎴" }
        ]
    },
    {
        id: '6',
        category: 'Travel & Places',
        icon: DirectionsCarOutlined,
        emojis: [
            { title: "automobile", emoji: "🚗" },
            { title: "taxi", emoji: "🚕" },
            { title: "sport utility vehicle", emoji: "🚙" },
            { title: "pickup truck", emoji: "🛻" },
            { title: "delivery truck", emoji: "🚚" },
            { title: "articulated lorry", emoji: "🚛" },
            { title: "tractor", emoji: "🚜" },
            { title: "racing car", emoji: "🏎️" },
            { title: "motorcycle", emoji: "🏍️" },
            { title: "scooter", emoji: "🛵" },
            { title: "manual wheelchair", emoji: "🦼" },
            { title: "motorized wheelchair", emoji: "🦽" },
            { title: "bus", emoji: "🚌" },
            { title: "oncoming bus", emoji: "🚍" },
            { title: "trolleybus", emoji: "🚎" },
            { title: "minibus", emoji: "🚐" },
            { title: "ambulance", emoji: "🚑" },
            { title: "fire engine", emoji: "🚒" },
            { title: "police car", emoji: "🚓" },
            { title: "oncoming police car", emoji: "🚔" },
            { title: "oncoming taxi", emoji: "🚖" },
            { title: "oncoming automobile", emoji: "🚘" },
            { title: "recreational vehicle", emoji: "🏕️" },
            { title: "motorway", emoji: "🛣️" },
            { title: "railway track", emoji: "🛤️" },
            { title: "oil drum", emoji: "🛢️" },
            { title: "fuel pump", emoji: "⛽" },
            { title: "vertical traffic light", emoji: "🚦" },
            { title: "horizontal traffic light", emoji: "🚥" },
            { title: "construction", emoji: "🚧" },
            { title: "anchor", emoji: "⚓" },
            { title: "sailboat", emoji: "⛵" },
            { title: "canoe", emoji: "🛶" },
            { title: "speedboat", emoji: "🚤" },
            { title: "passenger ship", emoji: "🛳️" },
            { title: "ferry", emoji: "🚢" },
            { title: "motor boat", emoji: "🛥️" },
            { title: "ship", emoji: "⛴️" },
            { title: "airplane", emoji: "✈️" },
            { title: "small airplane", emoji: "🛩️" },
            { title: "airplane departure", emoji: "🛫" },
            { title: "airplane arrival", emoji: "🛬" },
            { title: "seat", emoji: "💺" },
            { title: "helicopter", emoji: "🚁" },
            { title: "suspension railway", emoji: "🚟" },
            { title: "mountain cableway", emoji: "🚠" },
            { title: "aerial tramway", emoji: "🚡" },
            { title: "satellite", emoji: "🛰️" },
            { title: "rocket", emoji: "🚀" },
            { title: "flying saucer", emoji: "🛸" },
            { title: "train", emoji: "🚆" },
            { title: "high-speed train", emoji: "🚄" },
            { title: "bullet train", emoji: "🚅" },
            { title: "train", emoji: "🚂" },
            { title: "metro", emoji: "🚇" },
            { title: "light rail", emoji: "🚈" },
            { title: "station", emoji: "🚉" },
            { title: "tram", emoji: "🚊" },
            { title: "monorail", emoji: "🚝" },
            { title: "mountain railway", emoji: "🚞" },
            { title: "tram car", emoji: "🚋" },
            { title: "escalator", emoji: "🚻" },
            { title: "bus stop", emoji: "🚏" },
            { title: "map of japan", emoji: "🗾" },
            { title: "hot springs", emoji: "♨️" },
            { title: "tent", emoji: "⛺" },
            { title: "carousel horse", emoji: "🎠" },
            { title: "ferris wheel", emoji: "🎡" },
            { title: "roller coaster", emoji: "🎢" },
            { title: "barber pole", emoji: "💈" },
            { title: "circus tent", emoji: "🎪" },
            { title: "locomotive", emoji: "🚂" },
            { title: "house", emoji: "🏠" },
            { title: "house with garden", emoji: "🏡" },
            { title: "derelict house", emoji: "🏚️" },
            { title: "building", emoji: "🏢" },
            { title: "post office", emoji: "🏣" },
            { title: "european post office", emoji: "🏤" },
            { title: "hospital", emoji: "🏥" },
            { title: "bank", emoji: "🏦" },
            { title: "hotel", emoji: "🏨" },
            { title: "love hotel", emoji: "🏩" },
            { title: "convenience store", emoji: "🏪" },
            { title: "school", emoji: "🏫" },
            { title: "department store", emoji: "🏬" },
            { title: "factory", emoji: "🏭" },
            { title: "japanese castle", emoji: "🏯" },
            { title: "castle", emoji: "🏰" },
            { title: "wedding", emoji: "💒" },
            { title: "tokyo tower", emoji: "🗼" },
            { title: "statue of liberty", emoji: "🗽" },
            { title: "church", emoji: "⛪" },
            { title: "mosque", emoji: "🕌" },
            { title: "hindu temple", emoji: "🛕" },
            { title: "synagogue", emoji: "🕍" },
            { title: "kaaba", emoji: "🕋" },
            { title: "fountain", emoji: "⛲" },
            { title: "cityscape", emoji: "🏙️" },
            { title: "night with stars", emoji: "🌃" },
            { title: "sunset", emoji: "🌇" },
            { title: "sunrise", emoji: "🌅" },
            { title: "bridge at night", emoji: "🌉" },
            { title: "foggy", emoji: "🌁" },
            { title: "milky way", emoji: "🌌" },
            { title: "snowy mountain", emoji: "🏔️" },
            { title: "mountain", emoji: "⛰️" },
            { title: "volcano", emoji: "🌋" },
            { title: "desert", emoji: "🏜️" },
            { title: "beach with umbrella", emoji: "⛱️" },
            { title: "national park", emoji: "🏞️" },
            { title: "stadium", emoji: "🏟️" },
            { title: "classical building", emoji: "🏛️" },
            { title: "dormitory", emoji: "🛏️" },
            { title: "world map", emoji: "🗺️" },
            { title: "globe showing asia-australia", emoji: "🌏" },
            { title: "globe showing europe-africa", emoji: "🌍" },
            { title: "globe showing americas", emoji: "🌎" },
            { title: "park", emoji: "🅿️" },
            { title: "restroom", emoji: "🚻" },
            { title: "water closet", emoji: "🚾" },
            { title: "shower", emoji: "🚿" },
            { title: "bathtub", emoji: "🛁" },
            { title: "door", emoji: "🚪" },
            { title: "bellhop bell", emoji: "🛎️" },
            { title: "luggage", emoji: "🧳" },
            { title: "hourglass done", emoji: "⌛" },
            { title: "hourglass with flowing sand", emoji: "⏳" },
            { title: "watch", emoji: "⌚" },
            { title: "alarm clock", emoji: "⏰" },
            { title: "stopwatch", emoji: "⏱️" },
            { title: "timer clock", emoji: "⏲️" },
            { title: "mantelpiece clock", emoji: "🕰️" },
            { title: "twelve o’clock", emoji: "🕛" },
            { title: "twelve-thirty", emoji: "🕧" },
            { title: "one o’clock", emoji: "🕐" },
            { title: "one-thirty", emoji: "🕜" },
            { title: "two o’clock", emoji: "🕑" },
            { title: "two-thirty", emoji: "🕝" },
            { title: "three o’clock", emoji: "🕒" },
            { title: "three-thirty", emoji: "🕞" },
            { title: "four o’clock", emoji: "🕓" },
            { title: "four-thirty", emoji: "🕟" },
            { title: "five o’clock", emoji: "🕔" },
            { title: "five-thirty", emoji: "🕠" },
            { title: "six o’clock", emoji: "🕕" },
            { title: "six-thirty", emoji: "🕡" },
            { title: "seven o’clock", emoji: "🕖" },
            { title: "seven-thirty", emoji: "🕢" },
            { title: "eight o’clock", emoji: "🕗" },
            { title: "eight-thirty", emoji: "🕣" },
            { title: "nine o’clock", emoji: "🕘" },
            { title: "nine-thirty", emoji: "🕤" },
            { title: "ten o’clock", emoji: "🕙" },
            { title: "ten-thirty", emoji: "🕥" },
            { title: "eleven o’clock", emoji: "🕚" },
            { title: "eleven-thirty", emoji: "🕦" }
        ]
    },
    {
        id: '7',
        category: 'Objects',
        icon: EmojiObjectsOutlined,
        emojis: [
            { title: "light bulb", emoji: "💡" },
            { title: "flashlight", emoji: "🔦" },
            { title: "desk lamp", emoji: "🪔" },
            { title: "book", emoji: "📖" },
            { title: "open book", emoji: "📚" },
            { title: "notebook", emoji: "📓" },
            { title: "notebook with decorative cover", emoji: "📔" },
            { title: "green book", emoji: "📗" },
            { title: "blue book", emoji: "📘" },
            { title: "orange book", emoji: "📙" },
            { title: "books", emoji: "📕" },
            { title: "bookmark", emoji: "🔖" },
            { title: "label", emoji: "🏷️" },
            { title: "money bag", emoji: "💰" },
            { title: "yen banknote", emoji: "💴" },
            { title: "dollar banknote", emoji: "💵" },
            { title: "euro banknote", emoji: "💶" },
            { title: "pound banknote", emoji: "💷" },
            { title: "credit card", emoji: "💳" },
            { title: "receipt", emoji: "🧾" },
            { title: "chart increasing with yen", emoji: "💹" },
            { title: "envelope", emoji: "✉️" },
            { title: "e-mail", emoji: "📧" },
            { title: "inbox tray", emoji: "📥" },
            { title: "outbox tray", emoji: "📤" },
            { title: "envelope with arrow", emoji: "📩" },
            { title: "incoming envelope", emoji: "📨" },
            { title: "love letter", emoji: "💌" },
            { title: "postbox", emoji: "📮" },
            { title: "closed mailbox with raised flag", emoji: "📪" },
            { title: "closed mailbox with lowered flag", emoji: "📫" },
            { title: "open mailbox with raised flag", emoji: "📬" },
            { title: "open mailbox with lowered flag", emoji: "📭" },
            { title: "package", emoji: "📦" },
            { title: "handshake", emoji: "🤝" },
            { title: "pen", emoji: "🖊️" },
            { title: "black nib", emoji: "✒️" },
            { title: "fountain pen", emoji: "🖋️" },
            { title: "pencil", emoji: "✏️" },
            { title: "crayon", emoji: "🖍️" },
            { title: "paintbrush", emoji: "🖌️" },
            { title: "memo", emoji: "📝" },
            { title: "file folder", emoji: "📁" },
            { title: "open file folder", emoji: "📂" },
            { title: "card index dividers", emoji: "🗂️" },
            { title: "date window", emoji: "📅" },
            { title: "calendar", emoji: "🗓️" },
            { title: "spiral notepad", emoji: "🗒️" },
            { title: "spiral calendar", emoji: "🗓️" },
            { title: "card index", emoji: "📇" },
            { title: "chart increasing", emoji: "📈" },
            { title: "chart decreasing", emoji: "📉" },
            { title: "bar chart", emoji: "📊" },
            { title: "clipboard", emoji: "📋" },
            { title: "pushpin", emoji: "📌" },
            { title: "round pushpin", emoji: "📍" },
            { title: "paperclip", emoji: "📎" },
            { title: "linked paperclips", emoji: "🖇️" },
            { title: "straight ruler", emoji: "📏" },
            { title: "triangular ruler", emoji: "📐" },
            { title: "scissors", emoji: "✂️" },
            { title: "card file box", emoji: "🗃️" },
            { title: "file cabinet", emoji: "🗄️" },
            { title: "wastebasket", emoji: "🗑️" },
            { title: "locked", emoji: "🔒" },
            { title: "unlocked", emoji: "🔓" },
            { title: "lock with key", emoji: "🔏" },
            { title: "key", emoji: "🔑" },
            { title: "old key", emoji: "🗝️" },
            { title: "hammer", emoji: "🔨" },
            { title: "axe", emoji: "🪓" },
            { title: "pick", emoji: "⛏️" },
            { title: "hammer and pick", emoji: "⚒️" },
            { title: "hammer and wrench", emoji: "🛠️" },
            { title: "dagger", emoji: "🗡️" },
            { title: "crossed swords", emoji: "⚔️" },
            { title: "pistol", emoji: "🔫" },
            { title: "bow and arrow", emoji: "🏹" },
            { title: "shield", emoji: "🛡️" },
            { title: "wrench", emoji: "🔧" },
            { title: "nut and bolt", emoji: "🔩" },
            { title: "gear", emoji: "⚙️" },
            { title: "clamp", emoji: "🗜️" },
            { title: "balance scale", emoji: "⚖️" },
            { title: "chains", emoji: "⛓️" },
            { title: "magnet", emoji: "🧲" },
            { title: "alembic", emoji: "⚗️" },
            { title: "test tube", emoji: "🧪" },
            { title: "petri dish", emoji: "🧫" },
            { title: "dna", emoji: "🧬" },
            { title: "microscope", emoji: "🔬" },
            { title: "telescope", emoji: "🔭" },
            { title: "satellite antenna", emoji: "📡" },
            { title: "syringe", emoji: "💉" },
            { title: "drop of blood", emoji: "🩸" },
            { title: "pill", emoji: "💊" },
            { title: "adhesive bandage", emoji: "🩹" },
            { title: "stethoscope", emoji: "🩺" },
            { title: "door", emoji: "🚪" },
            { title: "bed", emoji: "🛏️" },
            { title: "couch and lamp", emoji: "🛋️" },
            { title: "chair", emoji: "🪑" },
            { title: "toilet", emoji: "🚽" },
            { title: "shower", emoji: "🚿" },
            { title: "bathtub", emoji: "🛁" },
            { title: "razor", emoji: "🪒" },
            { title: "lotion bottle", emoji: "🧴" },
            { title: "safety pin", emoji: "🧷" },
            { title: "broom", emoji: "🧹" },
            { title: "basket", emoji: "🧺" },
            { title: "roll of paper", emoji: "🧻" },
            { title: "bucket", emoji: "🪣" },
            { title: "soap", emoji: "🧼" },
            { title: "sponge", emoji: "🧽" },
            { title: "fire extinguisher", emoji: "🧯" },
            { title: "shopping cart", emoji: "🛒" },
            { title: "cigarette", emoji: "🚬" },
            { title: "coffin", emoji: "⚰️" },
            { title: "headstone", emoji: "🪦" },
            { title: "urn", emoji: "⚱️" },
            { title: "nazar amulet", emoji: "🧿" },
            { title: "crystal ball", emoji: "🔮" },
            { title: "prayer beads", emoji: "📿" },
            { title: "gem stone", emoji: "💎" },
            { title: "ring", emoji: "💍" },
            { title: "test tube", emoji: "🧪" },
            { title: "desktop computer", emoji: "🖥️" },
            { title: "laptop", emoji: "💻" },
            { title: "keyboard", emoji: "⌨️" },
            { title: "computer mouse", emoji: "🖱️" },
            { title: "trackball", emoji: "🖲️" },
            { title: "printer", emoji: "🖨️" },
            { title: "computer disk", emoji: "💾" },
            { title: "floppy disk", emoji: "💽" },
            { title: "optical disk", emoji: "💿" },
            { title: "dvd", emoji: "📀" },
            { title: "abacus", emoji: "🧮" },
            { title: "movie camera", emoji: "🎥" },
            { title: "film frames", emoji: "🎞️" },
            { title: "film projector", emoji: "📽️" },
            { title: "telephone receiver", emoji: "📞" },
            { title: "mobile phone", emoji: "📱" },
            { title: "telephone", emoji: "☎️" },
            { title: "pager", emoji: "📟" },
            { title: "fax machine", emoji: "📠" },
            { title: "radio", emoji: "📻" },
            { title: "microphone", emoji: "🎤" },
            { title: "headphone", emoji: "🎧" },
            { title: "level slider", emoji: "🎚️" },
            { title: "control knobs", emoji: "🎛️" },
            { title: "alarm clock", emoji: "⏰" },
            { title: "hourglass done", emoji: "⌛" },
            { title: "hourglass with flowing sand", emoji: "⏳" },
            { title: "battery", emoji: "🔋" },
            { title: "electric plug", emoji: "🔌" },
            { title: "magnifying glass tilted left", emoji: "🔍" },
            { title: "magnifying glass tilted right", emoji: "🔎" },
            { title: "locked with pen", emoji: "🔏" },
            { title: "key", emoji: "🔑" },
            { title: "lock", emoji: "🔒" },
            { title: "unlocked", emoji: "🔓" },
            { title: "closed lock with key", emoji: "🔐" },
            { title: "hammer", emoji: "🔨" },
            { title: "pick", emoji: "⛏️" },
            { title: "wrench", emoji: "🔧" },
            { title: "nut and bolt", emoji: "🔩" },
            { title: "gear", emoji: "⚙️" },
            { title: "chains", emoji: "⛓️" },
            { title: "clamp", emoji: "🗜️" },
            { title: "telescope", emoji: "🔭" },
            { title: "microscope", emoji: "🔬" },
            { title: "ringed planet", emoji: "🪐" },
            { title: "satellite antenna", emoji: "📡" },
            { title: "rocket", emoji: "🚀" },
            { title: "flying saucer", emoji: "🛸" },
            { title: "syringe", emoji: "💉" },
            { title: "pill", emoji: "💊" },
            { title: "door", emoji: "🚪" },
            { title: "bellhop bell", emoji: "🛎️" },
            { title: "luggage", emoji: "🧳" },
            { title: "map", emoji: "🗺️" },
            { title: "compass", emoji: "🧭" }
        ]
    },
    {
        id: '8',
        category: 'Symbols',
        icon: EmojiSymbolsOutlined,
        emojis: []
    },
    {
        id: '9',
        category: 'Flags',
        icon: FlagOutlined,
        emojis: []
    },
];